spring:
  application:
    name: AkSB

  profiles:
    active: dev

  data:
    mongodb:
      port: 27017
      uri: 
      database: journaldb
      auto-index-creation: true
      # host: localhost
      # username: abc
      # password: abc
