spring:
  application:
    name: AkSB

 # profiles:
  #  active: dev

  data:
    mongodb:
      port: 27017
      uri:
      database: journaldb
      auto-index-creation: true
      # host: localhost
      # username: abc
      # password: abc
  mail:
    host: smtp.gmail.com
    port: 587
    username: your_email@gmail.com
    password: your_app_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8082
  servlet:
    context-path: /journal